version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: tripcok_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tripcok_db
      MYSQL_USER: tripcok
      MYSQL_PASSWORD: tripcok1234
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ~/.mariadb/:/var/lib/mysql

volumes:
  mariadb_data:
