spring:
  datasource:
    url: jdbc:mariadb://192.168.0.5:3306/tripcok_db
    username: tripcok
    password: tripcok1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect


save:
  location:
    place-thumbnail: ~/