spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mariadb://${DB_HOST_IP}:${DB_HOST_PORT}/${DB_HOST_DATABASE}
    username: ${DB_HOST_USERNAME}
    password: ${DB_HOST_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: false
        format_sql: false

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,public/**

#
#  kafka:
#    producer:
#      bootstrap-servers: 172.31.5.40:29092,172.31.5.40:39092,172.31.5.40:49092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#      acks: all       # 모든 복제 브로커의 응답을 기다림
#      retries: 3      # 재시도 횟수
#      enable-idempotence: true # 멱등성 활성화

mail:
  username: ${MAIL_USER_NAME}
  password: ${MAIL_USER_PASSWORD}


save:
  location:
    place: place/images
    user:
      profile: user/profile

logging:
  config: classpath:logging/spring-log-local.xml

cloud:
  aws:
    s3:
      bucket: tripcok
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

server:
  port: 9090


