spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mariadb://localhost:3366/tripcok_db
    username: tripcok
    password: tripcok1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: false
        format_sql: false

mail:
  username: ukidd12@naver.com
  password: ljh90140189!


save:
  location:
    place: /place-image
    user:
      profile: /user/profile
logging:
  config: classpath:logging/spring_log.xml
